version: '3.8'

services:
  # Сервіс бекенду на FastAPI
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        - REQUIREMENTS_FILE=requirements.docker.txt
    container_name: ai-analytic-backend
    ports:
      - "0.0.0.0:${BACKEND_PORT:-8001}:8000"
    volumes:
      - .:/app
      - ./.env:/app/.env
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./batteries.db}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - BACKEND_PORT=${BACKEND_PORT:-8000}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      - HTTPS=true
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --ssl-keyfile /ssl_certs/key.pem --ssl-certfile /ssl_certs/cert.pem --reload
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Сервіс фронтенду на React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: ai-analytic-frontend
    ports:
      - "0.0.0.0:${FRONTEND_PORT:-3001}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./.env:/app/.env
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://backend:8000}
      - NODE_ENV=development
      - WDS_SOCKET_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - HTTPS=true
      - WDS_SOCKET_PORT=443
    command: npm start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
