"""add proce per w

Revision ID: 4b8861579acf
Revises: 07ee56d57592
Create Date: 2025-05-19 14:39:38.426631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8861579acf'
down_revision: Union[str, None] = '07ee56d57592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sollar_panels', sa.Column('price_per_w', sa.Float(), nullable=False))
    op.add_column('sollar_panels_current', sa.Column('price_per_w', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sollar_panels_current', 'price_per_w')
    op.drop_column('sollar_panels', 'price_per_w')
    # ### end Alembic commands ###
