"""fix

Revision ID: 5c76f674cd21
Revises: 9f2379ea7284
Create Date: 2025-05-01 14:37:56.629020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c76f674cd21'
down_revision: Union[str, None] = '9f2379ea7284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batteries', sa.Column('c_amps', sa.Integer(), nullable=False))
    op.add_column('batteries', sa.Column('region', sa.String(), nullable=False))
    op.add_column('batteries', sa.Column('polarity', sa.String(), nullable=False))
    op.add_column('batteries', sa.Column('electrolyte', sa.String(), nullable=False))
    op.add_column('current_batteries', sa.Column('c_amps', sa.Integer(), nullable=False))
    op.add_column('current_batteries', sa.Column('region', sa.String(), nullable=False))
    op.add_column('current_batteries', sa.Column('polarity', sa.String(), nullable=False))
    op.add_column('current_batteries', sa.Column('electrolyte', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_batteries', 'electrolyte')
    op.drop_column('current_batteries', 'polarity')
    op.drop_column('current_batteries', 'region')
    op.drop_column('current_batteries', 'c_amps')
    op.drop_column('batteries', 'electrolyte')
    op.drop_column('batteries', 'polarity')
    op.drop_column('batteries', 'region')
    op.drop_column('batteries', 'c_amps')
    # ### end Alembic commands ###
