"""add inverters

Revision ID: 7929f2f89d2b
Revises: 4b8861579acf
Create Date: 2025-05-29 16:40:10.659375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7929f2f89d2b'
down_revision: Union[str, None] = '4b8861579acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_inverters', sa.Column('power', sa.Float(), nullable=False))
    op.add_column('inverters', sa.Column('inverter_type', sa.String(), nullable=False))
    op.add_column('inverters', sa.Column('generation', sa.String(), nullable=False))
    op.add_column('inverters', sa.Column('string_count', sa.Integer(), nullable=False))
    op.add_column('inverters', sa.Column('firmware', sa.String(), nullable=False))
    op.add_column('inverters', sa.Column('power', sa.Float(), nullable=False))
    op.add_column('inverters', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('inverters', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.add_column('inverters', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'inverters', 'inverters_suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'inverters', 'inverters_brands', ['brand_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inverters', type_='foreignkey')
    op.drop_constraint(None, 'inverters', type_='foreignkey')
    op.drop_column('inverters', 'created_at')
    op.drop_column('inverters', 'supplier_id')
    op.drop_column('inverters', 'brand_id')
    op.drop_column('inverters', 'power')
    op.drop_column('inverters', 'firmware')
    op.drop_column('inverters', 'string_count')
    op.drop_column('inverters', 'generation')
    op.drop_column('inverters', 'inverter_type')
    op.drop_column('current_inverters', 'power')
    # ### end Alembic commands ###
