"""fix

Revision ID: 8f18cc016455
Revises: 5c76f674cd21
Create Date: 2025-05-01 15:07:58.461787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f18cc016455'
down_revision: Union[str, None] = '5c76f674cd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batteries', 'c_amps',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('batteries', 'c_amps',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
